/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ArtBlockContract } from "./ArtBlockContract";

export { ArtBlockContract__factory } from "./factories/ArtBlockContract__factory";
